// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlbtaungfhcszwoihppf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsYnRhdW5nZmhjc3p3b2locHBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTQ4ODgsImV4cCI6MjA3MTE5MDg4OH0.A7nWLJIHbPV-_bqNX8n3FNVRUDP8yCxI-0kTbfkoei0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});